// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://vptagnlbunmjolorjhnl.supabase.co'
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwdGFnbmxidW5tam9sb3JqaG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODI1MTgsImV4cCI6MjA3NDU1ODUxOH0.auvGSukyNzCFdOE0dlCC0RiYeDIH_jSgB0wTeAY5oME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);